# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QFont, QFontDatabase, QMovie


class MyFont(QFont):
    """
    define my font
    Consolas-Italic.ttf
    """

    def __init__(self, parent=None):
        super(MyFont, self).__init__()
        font_id = QFontDatabase.addApplicationFont('static/Consolas-Italic.ttf')
        # font_id = QFontDatabase.addApplicationFont('./Font/Roboto-Black.ttf')

        self.setFamily(QFontDatabase.applicationFontFamilies(font_id)[0])
        self.setItalic(True)
        self.setBold(True)  # 粗体
        self.setPixelSize(22)  # 字体大小


class MyLabel(QtWidgets.QLabel):
    """
    In order to make the label inherit a set of fonts I define custom label
    """

    def __init__(self, parent=None):
        QtWidgets.QLabel.__init__(self, parent)
        my_font = MyFont()
        self.setFont(my_font)
        self.setStyleSheet("color:#8d6e63")


class OrangeLabel(MyLabel):
    def __init__(self, parent=None):
        MyLabel.__init__(self, parent)
        self.setStyleSheet("color:#ff9e80")


class MyButton(QtWidgets.QPushButton):
    def __init__(self, parent=None):
        QtWidgets.QPushButton.__init__(self, parent)
        # self.setStyleSheet(r"background-color: cadetblue;color:#afb42b")
        with open(r'static\main.qss', 'r', encoding='utf-8') as fp:
            self.setStyleSheet(fp.read())
            fp.close()




class Ui_MainWindow(object):
    font = None
    isNotHelp = True
    isWaked = False

    def update_widget(self):
        self.widget.setVisible(self.isNotHelp and (not self.isWaked))
        self.widget_2.setVisible(not self.isNotHelp)
        self.widget_3.setVisible(self.isNotHelp and self.isWaked)
        if self.isWaked:
            self.pushButton.setText("Return to chat with me")


    def change_wake_sleep(self):
        self.isWaked = not self.isWaked
        self.update_widget()

    def change_main_help(self):
        """
        change_main_help user interface
        :return:
        """
        self.isNotHelp = not self.isNotHelp
        self.update_widget()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setStyleSheet("background-color: rgb(255, 255,255);")
        MainWindow.resize(700, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # First widget
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 700, 800))
        self.widget.setObjectName("widget")
        self.label_3 = MyLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(180, 520, 400, 70))
        self.label_3.setObjectName("label_3")
        # self.label_3.setFont(self.font)
        self.helpButton = MyButton(self.widget)
        self.helpButton.clicked.connect(self.change_main_help)
        self.helpButton.setGeometry(QtCore.QRect(230, 420, 240, 60))
        self.helpButton.setObjectName("helpButton")
        self.label = MyLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(180, 320, 400, 40))
        self.label.setObjectName("label")

        # The third widget, the main window
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 700, 800))
        self.widget_3.setObjectName("widget_3")
        self.label_1 = MyLabel(self.widget_3)
        self.label_1.setGeometry(QtCore.QRect(235, 320, 400, 40))
        self.label_1.setObjectName("label_1")

        self.label_3_1 = MyLabel(self.widget_3)
        self.label_3_1.setGeometry(QtCore.QRect(235, 420, 500, 70))
        self.label_3_1.setObjectName("label_3_1")

        self.sleepButton = MyButton(self.widget_3)
        self.sleepButton.clicked.connect(self.change_main_help)
        self.sleepButton.setGeometry(QtCore.QRect(230, 520, 240, 60))
        self.sleepButton.setObjectName("sleepButton")

        # the second widget
        self.widget_2 = QtWidgets.QWidget(MainWindow)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 700, 800))
        self.widget_2.setObjectName("widget_2")
        self.label_5 = OrangeLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(190, 250, 400, 40))
        self.label_5.setObjectName("label_5")
        self.label_2 = MyLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(120, 110, 400, 40))
        self.label_2.setObjectName("label_2")
        self.label_4 = MyLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(120, 50, 400, 40))
        self.label_4.setObjectName("label_4")
        self.label_6 = MyLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(120, 290, 400, 40))
        self.label_6.setObjectName("label_6")
        self.label_9 = OrangeLabel(self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(190, 410, 400, 40))
        self.label_9.setObjectName("label_9")
        self.label_11 = OrangeLabel(self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(190, 500, 400, 40))
        self.label_11.setObjectName("label_11")
        self.label_7 = OrangeLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(190, 330, 400, 40))
        self.label_7.setObjectName("label_7")
        self.label_8 = OrangeLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(190, 160, 400, 40))
        self.label_8.setObjectName("label_8")
        self.label_10 = MyLabel(self.widget_2)
        self.label_10.setGeometry(QtCore.QRect(120, 370, 400, 40))
        self.label_10.setObjectName("label_10")
        self.label_12 = MyLabel(self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(120, 200, 400, 40))
        self.label_12.setObjectName("label_12")
        self.label_13 = MyLabel(self.widget_2)
        self.label_13.setGeometry(QtCore.QRect(120, 450, 400, 40))
        self.label_13.setObjectName("label_13")
        self.pushButton = MyButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(130, 560, 400, 60))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.change_main_help)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Gif = QtWidgets.QLabel(self.widget)
        self.Gif.setGeometry(QtCore.QRect(150, 0, 400, 300))
        self.gif = QMovie(r"static\sleep.gif")
        self.Gif.setMovie(self.gif)
        self.gif.start()
        self.Gif.setScaledContents(True)
        self.Gif.setObjectName("sleep")

        self.Gif_2 = QtWidgets.QLabel(self.widget_2)
        self.Gif_2.setGeometry(QtCore.QRect(420, 220, 320, 240))
        self.gif_2 = QMovie(r"static\robot.gif")
        self.Gif_2.setMovie(self.gif_2)
        self.gif_2.start()
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("robot")
        self.update_widget()

        self.Gif_3 = QtWidgets.QLabel(self.widget_3)
        self.Gif_3.setGeometry(QtCore.QRect(180, 50, 360, 270))

        self.gif_3 = QMovie(r"static\robot.gif")
        self.Gif_3.setMovie(self.gif_3)
        self.gif_3.start()

        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("robot")
        self.update_widget()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", ""))
        self.label_3_1.setText(_translate("MainWindow", "What can I do for you?"))
        self.label_1.setText(_translate("MainWindow", "Nice to meet you!"))
        self.helpButton.setText(_translate("MainWindow", "Click for some help"))
        self.helpButton.setFont(MyFont())

        self.label.setText(_translate("MainWindow", "Say \"Hello\" to wake up me😃"))

        self.sleepButton.setText(_translate("MainWindow", "Click for Some tips"))
        self.sleepButton.setFont(MyFont())
        self.label_4.setText(_translate("MainWindow", "Some tips:"))
        self.label_2.setText(_translate("MainWindow", "1.Enjoy music by saying:"))
        self.label_6.setText(_translate("MainWindow", "3.Watch video by saying:"))
        self.label_10.setText(_translate("MainWindow", "4.Draw a picture by saying:"))
        self.label_12.setText(_translate("MainWindow", "2.Open notepad by saying:"))
        self.label_13.setText(_translate("MainWindow", "5.Do some math work by saying:"))
        self.pushButton.setText(_translate("MainWindow", "Return to wake up me"))
        self.pushButton.setFont(MyFont())
